const a='user';
const b='userAdress';
const c='userSport';
const user=prompt("Ваш рік народження?",0);
alert(user);
const userAdress=prompt("В якому місті живете?","Київ, Вашингтон,Лондон");
alert('Ти живешь у столиці'+ userAdress);
alert('Ти живешь у місті'+ userAdress);
const userSport=prompt("Ваш улюблений від спорту?",0);
alert(userSport);
const d = 'userChampion';
const userChampion=prompt("Виберить один із ціх видів спорту:легка атлетіка,бокс,фигурне катаня");
alert(userChampion);